version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: geodb
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopassword
    ports:
      - "5455:5432"

  web:
    build: .
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=geodb
      - DATABASE_USER=geouser
      - DATABASE_PASSWORD=geopassword
      - DATABASE_HOST=db
